name: Build and Publish to PyPi

on:
  push:
    tags:
      - 'v*'
jobs:
  build-n-publish:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.12'
      
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build binary wheel and source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish distribution to PyPi
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@1.8.14
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
